collections_dir: my_collections

collections:
  categories:
    output: true
  documents:
    output: true
  mono1:
    output: true
  mono2:
    output: true    

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "categories"
  - scope:
      path: ""
    values:
      layout: "default"