collections:
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "categories"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"